# ============================================
# Test Credentials
# Put the login details your tests will use here.
# Beginners: just edit the 3 values below.
# ============================================

login.school.type=Secondary
login.username=brcm
login.password=ENC(jUm7u1MqZE0Wur58vRTpX/D98QZ42Zr0uspM71W2ZJweqHa3pUQW8lQQ/j9supXL)

