# -----------------------------
# Framework execution settings
# -----------------------------
browser=chrome
headless=false
window.maximize=true

implicit.wait.seconds=15
explicit.wait.seconds=60
page.load.timeout.seconds=30
retry.count=3
screenshot.on.pass=false

# -----------------------------
# UI settings
# -----------------------------
ui.base.url=https://demo.vtiger.com/vtigercrm/
ui.username=admin
ui.password=admin

# -----------------------------
# API settings
# -----------------------------
api.base.url=https://jsonplaceholder.typicode.com
api.user.endpoint=/users/1
api.create.user.endpoint=/users
api.auth.token=

# -----------------------------
# Database settings
# -----------------------------
db.url=jdbc:mysql://localhost:3306/vtiger
db.username=root
db.password=root

# -----------------------------
# Test data settings
# -----------------------------
testdata.path=src/test/java/data/TestData.xlsx
